export type CatalogGenre =
  | 'classics'
  | 'fiction'
  | 'fantasy'
  | 'science_fiction'
  | 'mystery'
  | 'thriller'
  | 'romance'
  | 'horror'
  | 'historical_fiction'
  | 'biography'
  | 'psychology'
  | 'self-help'
  | 'adventure'
  | 'young_adult'
  | 'nonfiction';

export interface CatalogBook {
  id: string;
  titleRu: string;
  titleEn: string;
  authorRu: string;
  authorEn: string;
  genre: CatalogGenre;
  genreRu: string;
  pages?: number;
}

const g = (
  id: string,
  titleRu: string,
  titleEn: string,
  authorRu: string,
  authorEn: string,
  genre: CatalogGenre,
  genreRu: string,
  pages?: number,
): CatalogBook => ({ id, titleRu, titleEn, authorRu, authorEn, genre, genreRu, pages });

/**
 * Curated popular books — recommendations come from here.
 * Covers are bundled in src/assets/catalogCovers (see scripts/downloadCatalogCovers.cjs).
 */
export const POPULAR_BOOKS_CATALOG: CatalogBook[] = [
  // —— Русская классика ——
  g('ru-class-001', 'Война и мир', 'War and Peace', 'Лев Толстой', 'Leo Tolstoy', 'classics', 'Классика', 1225),
  g('ru-class-002', 'Анна Каренина', 'Anna Karenina', 'Лев Толстой', 'Leo Tolstoy', 'classics', 'Классика', 864),
  g('ru-class-003', 'Преступление и наказание', 'Crime and Punishment', 'Фёдор Достоевский', 'Fyodor Dostoevsky', 'classics', 'Классика', 671),
  g('ru-class-004', 'Идиот', 'The Idiot', 'Фёдор Достоевский', 'Fyodor Dostoevsky', 'classics', 'Классика', 656),
  g('ru-class-005', 'Братья Карамазовы', 'The Brothers Karamazov', 'Фёдор Достоевский', 'Fyodor Dostoevsky', 'classics', 'Классика', 824),
  g('ru-class-006', 'Мастер и Маргарита', 'The Master and Margarita', 'Михаил Булгаков', 'Mikhail Bulgakov', 'classics', 'Классика', 480),
  g('ru-class-007', 'Собачье сердце', 'Heart of a Dog', 'Михаил Булгаков', 'Mikhail Bulgakov', 'classics', 'Классика', 128),
  g('ru-class-008', 'Евгений Онегин', 'Eugene Onegin', 'Александр Пушкин', 'Alexander Pushkin', 'classics', 'Классика', 240),
  g('ru-class-009', 'Герой нашего времени', 'A Hero of Our Time', 'Михаил Лермонтов', 'Mikhail Lermontov', 'classics', 'Классика', 192),
  g('ru-class-010', 'Мёртвые души', 'Dead Souls', 'Николай Гоголь', 'Nikolai Gogol', 'classics', 'Классика', 352),
  g('ru-class-011', 'Ревизор', 'The Government Inspector', 'Николай Гоголь', 'Nikolai Gogol', 'classics', 'Классика', 160),
  g('ru-class-012', 'Отцы и дети', 'Fathers and Sons', 'Иван Тургенев', 'Ivan Turgenev', 'classics', 'Классика', 288),
  g('ru-class-013', 'Обломов', 'Oblomov', 'Иван Гончаров', 'Ivan Goncharov', 'classics', 'Классика', 640),
  g('ru-class-014', 'Вишнёвый сад', 'The Cherry Orchard', 'Антон Чехов', 'Anton Chekhov', 'classics', 'Классика', 112),
  g('ru-class-015', 'Палата № 6', 'Ward No. 6', 'Антон Чехов', 'Anton Chekhov', 'classics', 'Классика', 96),
  g('ru-class-016', 'Тихий Дон', 'And Quiet Flows the Don', 'Михаил Шолохов', 'Mikhail Sholokhov', 'classics', 'Классика', 1360),
  g('ru-class-017', 'Доктор Живаго', 'Doctor Zhivago', 'Борис Пастернак', 'Boris Pasternak', 'classics', 'Классика', 592),
  g(
    'ru-class-018',
    'Один день Ивана Денисовича',
    'One Day in the Life of Ivan Denisovich',
    'Александр Солженицын',
    'Aleksandr Solzhenitsyn',
    'classics',
    'Классика',
    176,
  ),
  g('ru-class-019', 'Архипелаг ГУЛАГ', 'The Gulag Archipelago', 'Александр Солженицын', 'Aleksandr Solzhenitsyn', 'nonfiction', 'Нон-фикшн', 1424),
  g('ru-class-020', 'Мы', 'We', 'Евгений Замятин', 'Yevgeny Zamyatin', 'science_fiction', 'Научная фантастика', 256),

  // —— Современная русская проза ——
  g('ru-fic-001', 'Generation «П»', 'Homo Zapiens', 'Виктор Пелевин', 'Victor Pelevin', 'fiction', 'Художественная литература', 336),
  g('ru-fic-002', 'Чапаев и Пустота', "Buddha's Little Finger", 'Виктор Пелевин', 'Victor Pelevin', 'fiction', 'Художественная литература', 416),
  g('ru-fic-003', 'Empire V', 'Empire V', 'Виктор Пелевин', 'Victor Pelevin', 'fiction', 'Художественная литература', 416),
  g('ru-fic-004', 'Зулейха открывает глаза', 'Zuleikha', 'Гузель Яхина', 'Guzel Yakhina', 'historical_fiction', 'Историческая проза', 508),
  g('ru-fic-005', 'Дети мои', 'My Children', 'Гузель Яхина', 'Guzel Yakhina', 'historical_fiction', 'Историческая проза', 496),
  g('ru-fic-006', 'Лавр', 'Laurus', 'Евгений Водолазкин', 'Eugene Vodolazkin', 'fiction', 'Художественная литература', 440),
  g('ru-fic-007', 'Авиатор', 'The Aviator', 'Евгений Водолазкин', 'Eugene Vodolazkin', 'fiction', 'Художественная литература', 416),
  g('ru-fic-008', 'Казус Кукоцкого', 'The Kukotsky Case', 'Людмила Улицкая', 'Lyudmila Ulitskaya', 'fiction', 'Художественная литература', 512),
  g('ru-fic-009', 'Зелёный шатёр', 'The Big Green Tent', 'Людмила Улицкая', 'Lyudmila Ulitskaya', 'fiction', 'Художественная литература', 592),
  g('ru-fic-010', 'Санькя', 'Sankya', 'Захар Прилепин', 'Zakhar Prilepin', 'fiction', 'Художественная литература', 368),
  g('ru-fic-011', 'Обитель', 'The Monastery', 'Захар Прилепин', 'Zakhar Prilepin', 'historical_fiction', 'Историческая проза', 752),
  g('ru-fic-012', 'Текст', 'Text', 'Дмитрий Глуховский', 'Dmitry Glukhovsky', 'thriller', 'Триллер', 320),
  g('ru-fic-013', 'Метро 2033', 'Metro 2033', 'Дмитрий Глуховский', 'Dmitry Glukhovsky', 'science_fiction', 'Научная фантастика', 384),
  g('ru-fic-014', 'Метро 2034', 'Metro 2034', 'Дмитрий Глуховский', 'Dmitry Glukhovsky', 'science_fiction', 'Научная фантастика', 384),
  g('ru-fic-015', 'Метро 2035', 'Metro 2035', 'Дмитрий Глуховский', 'Dmitry Glukhovsky', 'science_fiction', 'Научная фантастика', 416),
  g('ru-fic-016', 'Лёгкость', 'Lightness', 'Алексей Сальников', 'Alexey Salnikov', 'fiction', 'Художественная литература', 416),
  g(
    'ru-fic-017',
    'Петровы в гриппе и вокруг него',
    'The Petrovs in and Around the Flu',
    'Алексей Сальников',
    'Alexey Salnikov',
    'fiction',
    'Художественная литература',
    416,
  ),
  g('ru-fic-018', 'Жизнь Арсеньева', 'The Life of Arseniev', 'Иван Бунин', 'Ivan Bunin', 'classics', 'Классика', 320),
  g('ru-fic-019', 'Лолита', 'Lolita', 'Владимир Набоков', 'Vladimir Nabokov', 'classics', 'Классика', 336),
  g('ru-fic-020', 'Дар', 'The Gift', 'Владимир Набоков', 'Vladimir Nabokov', 'classics', 'Классика', 400),

  // —— Русское фэнтези / фантастика ——
  g('ru-fan-001', 'Ночной дозор', 'Night Watch', 'Сергей Лукьяненко', 'Sergei Lukyanenko', 'fantasy', 'Фэнтези', 448),
  g('ru-fan-002', 'Дневной дозор', 'Day Watch', 'Сергей Лукьяненко', 'Sergei Lukyanenko', 'fantasy', 'Фэнтези', 432),
  g('ru-fan-003', 'Сумеречный дозор', 'Twilight Watch', 'Сергей Лукьяненко', 'Sergei Lukyanenko', 'fantasy', 'Фэнтези', 416),
  g('ru-fan-004', 'Последний дозор', 'Last Watch', 'Сергей Лукьяненко', 'Sergei Lukyanenko', 'fantasy', 'Фэнтези', 400),
  g('ru-fan-005', 'Чистовик', 'Draft', 'Сергей Лукьяненко', 'Sergei Lukyanenko', 'fantasy', 'Фэнтези', 384),
  g('ru-fan-006', 'Алмазный меч, деревянный меч', 'The Diamond Sword, the Wooden Sword', 'Ник Перумов', 'Nick Perumov', 'fantasy', 'Фэнтези', 640),
  g('ru-fan-007', 'Воин', 'Warrior', 'Ник Перумов', 'Nick Perumov', 'fantasy', 'Фэнтези', 512),
  g('ru-fan-008', 'Волкодав', 'Wolfhound', 'Мария Семёнова', 'Maria Semyonova', 'fantasy', 'Фэнтези', 576),
  g('ru-fan-009', 'Волкодав. Право на поединок', 'Wolfhound: Right to a Duel', 'Мария Семёнова', 'Maria Semyonova', 'fantasy', 'Фэнтези', 512),
  g(
    'ru-fan-010',
    'Трудно быть богом',
    'Hard to Be a God',
    'Аркадий и Борис Стругацкие',
    'Arkady and Boris Strugatsky',
    'science_fiction',
    'Научная фантастика',
    256,
  ),
  g(
    'ru-fan-011',
    'Пикник на обочине',
    'Roadside Picnic',
    'Аркадий и Борис Стругацкие',
    'Arkady and Boris Strugatsky',
    'science_fiction',
    'Научная фантастика',
    224,
  ),
  g(
    'ru-fan-012',
    'Обитаемый остров',
    'Prisoners of Power',
    'Аркадий и Борис Стругацкие',
    'Arkady and Boris Strugatsky',
    'science_fiction',
    'Научная фантастика',
    416,
  ),
  g(
    'ru-fan-013',
    'Понедельник начинается в субботу',
    'Monday Begins on Saturday',
    'Аркадий и Борис Стругацкие',
    'Arkady and Boris Strugatsky',
    'science_fiction',
    'Научная фантастика',
    320,
  ),
  g('ru-fan-014', 'Час Быка', "The Bull's Hour", 'Иван Ефремов', 'Ivan Yefremov', 'science_fiction', 'Научная фантастика', 480),
  g(
    'ru-fan-015',
    'Туманность Андромеды',
    'Andromeda: A Space-Age Tale',
    'Иван Ефремов',
    'Ivan Yefremov',
    'science_fiction',
    'Научная фантастика',
    400,
  ),
  g('ru-fan-016', 'Человек-амфибия', 'The Amphibian Man', 'Александр Беляев', 'Alexander Belyaev', 'science_fiction', 'Научная фантастика', 224),
  g(
    'ru-fan-017',
    'Голова профессора Доуэля',
    "Professor Dowell's Head",
    'Александр Беляев',
    'Alexander Belyaev',
    'science_fiction',
    'Научная фантастика',
    192,
  ),
  g('ru-fan-018', 'Тайна третьей планеты', 'Alice: The Girl from Earth', 'Кир Булычёв', 'Kir Bulychev', 'science_fiction', 'Научная фантастика', 192),
  g('ru-fan-019', 'Сто лет тому вперёд', 'One Hundred Years Ahead', 'Кир Булычёв', 'Kir Bulychev', 'science_fiction', 'Научная фантастика', 224),
  g('ru-fan-020', 'Крадущийся в тени', 'Shadow Chaser', 'Алексей Пехов', 'Alexey Pehov', 'fantasy', 'Фэнтези', 480),

  // —— Детективы / триллеры RU ——
  g('ru-mys-001', 'Азазель', 'The Winter Queen', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 288),
  g('ru-mys-002', 'Турецкий гамбит', 'The Turkish Gambit', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 256),
  g('ru-mys-003', 'Левиафан', 'Murder on the Leviathan', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 256),
  g('ru-mys-004', 'Смерть Ахиллеса', 'The Death of Achilles', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 320),
  g('ru-mys-005', 'Статский советник', 'The State Counsellor', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 352),
  g('ru-mys-006', 'Коронация', 'The Coronation', 'Борис Акунин', 'Boris Akunin', 'mystery', 'Детектив', 352),
  g('ru-mys-007', 'Пиковая дама', 'The Queen of Spades', 'Александра Маринина', 'Alexandra Marinina', 'mystery', 'Детектив', 352),
  g('ru-mys-008', 'Иллюзия греха', 'Illusion of Sin', 'Александра Маринина', 'Alexandra Marinina', 'mystery', 'Детектив', 416),
  g('ru-mys-009', 'Персональный код', 'Personal Code', 'Татьяна Устинова', 'Tatyana Ustinova', 'mystery', 'Детектив', 352),
  g('ru-mys-010', 'Хроника гнусных времён', 'Chronicle of Vile Times', 'Татьяна Устинова', 'Tatyana Ustinova', 'mystery', 'Детектив', 384),
  g('ru-mys-011', 'Кровь нерожденных', 'Blood of the Unborn', 'Полина Дашкова', 'Polina Dashkova', 'thriller', 'Триллер', 480),
  g('ru-mys-012', 'Чувство льда', 'Sense of Ice', 'Полина Дашкова', 'Polina Dashkova', 'thriller', 'Триллер', 448),

  // —— Мировые бестселлеры (рус. названия) ——
  g('ww-001', '1984', '1984', 'Джордж Оруэлл', 'George Orwell', 'classics', 'Классика', 328),
  g('ww-002', 'Скотный двор', 'Animal Farm', 'Джордж Оруэлл', 'George Orwell', 'classics', 'Классика', 112),
  g('ww-003', 'Убить пересмешника', 'To Kill a Mockingbird', 'Харпер Ли', 'Harper Lee', 'classics', 'Классика', 336),
  g('ww-004', 'Великий Гэтсби', 'The Great Gatsby', 'Фрэнсис Скотт Фицджеральд', 'F. Scott Fitzgerald', 'classics', 'Классика', 180),
  g('ww-005', 'Над пропастью во ржи', 'The Catcher in the Rye', 'Джером Сэлинджер', 'J. D. Salinger', 'classics', 'Классика', 234),
  g('ww-006', 'Маленький принц', 'The Little Prince', 'Антуан де Сент-Экзюпери', 'Antoine de Saint-Exupéry', 'classics', 'Классика', 96),
  g('ww-007', 'Алхимик', 'The Alchemist', 'Пауло Коэльо', 'Paulo Coelho', 'fiction', 'Художественная литература', 208),
  g(
    'ww-008',
    'Сто лет одиночества',
    'One Hundred Years of Solitude',
    'Габриэль Гарсиа Маркес',
    'Gabriel García Márquez',
    'classics',
    'Классика',
    417,
  ),
  g('ww-009', 'Любовь во время чумы', 'Love in the Time of Cholera', 'Габриэль Гарсиа Маркес', 'Gabriel García Márquez', 'romance', 'Романтика', 368),
  g('ww-010', 'Имя розы', 'The Name of the Rose', 'Умберто Эко', 'Umberto Eco', 'mystery', 'Детектив', 592),
  g('ww-011', 'Три товарища', 'Three Comrades', 'Эрих Мария Ремарк', 'Erich Maria Remarque', 'classics', 'Классика', 480),
  g(
    'ww-012',
    'На Западном фронте без перемен',
    'All Quiet on the Western Front',
    'Эрих Мария Ремарк',
    'Erich Maria Remarque',
    'classics',
    'Классика',
    296,
  ),
  g('ww-013', 'Триумфальная арка', 'Arch of Triumph', 'Эрих Мария Ремарк', 'Erich Maria Remarque', 'classics', 'Классика', 464),
  g('ww-014', 'Парфюмер', 'Perfume', 'Патрик Зюскинд', 'Patrick Süskind', 'fiction', 'Художественная литература', 272),
  g('ww-015', 'Тень ветра', 'The Shadow of the Wind', 'Карлос Руис Сафон', 'Carlos Ruiz Zafón', 'mystery', 'Детектив', 512),
  g('ww-016', 'Код да Винчи', 'The Da Vinci Code', 'Дэн Браун', 'Dan Brown', 'thriller', 'Триллер', 480),
  g('ww-017', 'Ангелы и демоны', 'Angels & Demons', 'Дэн Браун', 'Dan Brown', 'thriller', 'Триллер', 480),
  g('ww-018', 'Инферно', 'Inferno', 'Дэн Браун', 'Dan Brown', 'thriller', 'Триллер', 480),
  g(
    'ww-019',
    'Шерлок Холмс. Собака Баскервилей',
    'The Hound of the Baskervilles',
    'Артур Конан Дойл',
    'Arthur Conan Doyle',
    'mystery',
    'Детектив',
    256,
  ),
  g('ww-020', 'Убийство в «Восточном экспрессе»', 'Murder on the Orient Express', 'Агата Кристи', 'Agatha Christie', 'mystery', 'Детектив', 288),
  g('ww-021', 'Десять негритят', 'And Then There Were None', 'Агата Кристи', 'Agatha Christie', 'mystery', 'Детектив', 272),
  g('ww-022', 'Смерть на Ниле', 'Death on the Nile', 'Агата Кристи', 'Agatha Christie', 'mystery', 'Детектив', 352),
  g('ww-023', 'Джейн Эйр', 'Jane Eyre', 'Шарлотта Бронте', 'Charlotte Brontë', 'classics', 'Классика', 532),
  g('ww-024', 'Гордость и предубеждение', 'Pride and Prejudice', 'Джейн Остин', 'Jane Austen', 'classics', 'Классика', 432),
  g('ww-025', 'Грозовой перевал', 'Wuthering Heights', 'Эмили Бронте', 'Emily Brontë', 'classics', 'Классика', 416),
  g('ww-026', 'Граф Монте-Кристо', 'The Count of Monte Cristo', 'Александр Дюма', 'Alexandre Dumas', 'adventure', 'Приключения', 1312),
  g('ww-027', 'Три мушкетёра', 'The Three Musketeers', 'Александр Дюма', 'Alexandre Dumas', 'adventure', 'Приключения', 704),
  g('ww-028', 'Отверженные', 'Les Misérables', 'Виктор Гюго', 'Victor Hugo', 'classics', 'Классика', 1488),
  g('ww-029', 'Собор Парижской Богоматери', 'The Hunchback of Notre-Dame', 'Виктор Гюго', 'Victor Hugo', 'classics', 'Классика', 656),
  g(
    'ww-030',
    'Приключения Шерлока Холмса',
    'The Adventures of Sherlock Holmes',
    'Артур Конан Дойл',
    'Arthur Conan Doyle',
    'mystery',
    'Детектив',
    320,
  ),

  // —— Фэнтези / SF мировые ——
  g(
    'ww-fan-001',
    'Властелин колец. Братство Кольца',
    'The Fellowship of the Ring',
    'Дж. Р. Р. Толкин',
    'J. R. R. Tolkien',
    'fantasy',
    'Фэнтези',
    576,
  ),
  g('ww-fan-002', 'Властелин колец. Две крепости', 'The Two Towers', 'Дж. Р. Р. Толкин', 'J. R. R. Tolkien', 'fantasy', 'Фэнтези', 448),
  g('ww-fan-003', 'Властелин колец. Возвращение короля', 'The Return of the King', 'Дж. Р. Р. Толкин', 'J. R. R. Tolkien', 'fantasy', 'Фэнтези', 512),
  g('ww-fan-004', 'Хоббит', 'The Hobbit', 'Дж. Р. Р. Толкин', 'J. R. R. Tolkien', 'fantasy', 'Фэнтези', 320),
  g(
    'ww-fan-005',
    'Гарри Поттер и философский камень',
    "Harry Potter and the Philosopher's Stone",
    'Джоан Роулинг',
    'J. K. Rowling',
    'fantasy',
    'Фэнтези',
    352,
  ),
  g(
    'ww-fan-006',
    'Гарри Поттер и Тайная комната',
    'Harry Potter and the Chamber of Secrets',
    'Джоан Роулинг',
    'J. K. Rowling',
    'fantasy',
    'Фэнтези',
    384,
  ),
  g(
    'ww-fan-007',
    'Гарри Поттер и узник Азкабана',
    'Harry Potter and the Prisoner of Azkaban',
    'Джоан Роулинг',
    'J. K. Rowling',
    'fantasy',
    'Фэнтези',
    448,
  ),
  g('ww-fan-008', 'Гарри Поттер и Кубок огня', 'Harry Potter and the Goblet of Fire', 'Джоан Роулинг', 'J. K. Rowling', 'fantasy', 'Фэнтези', 704),
  g(
    'ww-fan-009',
    'Гарри Поттер и Орден Феникса',
    'Harry Potter and the Order of the Phoenix',
    'Джоан Роулинг',
    'J. K. Rowling',
    'fantasy',
    'Фэнтези',
    896,
  ),
  g(
    'ww-fan-010',
    'Гарри Поттер и Принц-полукровка',
    'Harry Potter and the Half-Blood Prince',
    'Джоан Роулинг',
    'J. K. Rowling',
    'fantasy',
    'Фэнтези',
    672,
  ),
  g('ww-fan-011', 'Гарри Поттер и Дары Смерти', 'Harry Potter and the Deathly Hallows', 'Джоан Роулинг', 'J. K. Rowling', 'fantasy', 'Фэнтези', 784),
  g('ww-fan-012', 'Игра престолов', 'A Game of Thrones', 'Джордж Р. Р. Мартин', 'George R. R. Martin', 'fantasy', 'Фэнтези', 864),
  g('ww-fan-013', 'Битва королей', 'A Clash of Kings', 'Джордж Р. Р. Мартин', 'George R. R. Martin', 'fantasy', 'Фэнтези', 832),
  g('ww-fan-014', 'Буря мечей', 'A Storm of Swords', 'Джордж Р. Р. Мартин', 'George R. R. Martin', 'fantasy', 'Фэнтези', 992),
  g('ww-fan-015', 'Дюна', 'Dune', 'Фрэнк Герберт', 'Frank Herbert', 'science_fiction', 'Научная фантастика', 688),
  g('ww-fan-016', 'Основание', 'Foundation', 'Айзек Азимов', 'Isaac Asimov', 'science_fiction', 'Научная фантастика', 256),
  g('ww-fan-017', 'Я, робот', 'I, Robot', 'Айзек Азимов', 'Isaac Asimov', 'science_fiction', 'Научная фантастика', 256),
  g('ww-fan-018', '451 градус по Фаренгейту', 'Fahrenheit 451', 'Рэй Брэдбери', 'Ray Bradbury', 'science_fiction', 'Научная фантастика', 256),
  g('ww-fan-019', 'Марсианские хроники', 'The Martian Chronicles', 'Рэй Брэдбери', 'Ray Bradbury', 'science_fiction', 'Научная фантастика', 288),
  g('ww-fan-020', 'Конец вечности', 'The End of Eternity', 'Айзек Азимов', 'Isaac Asimov', 'science_fiction', 'Научная фантастика', 256),
  g(
    'ww-fan-021',
    'Автостопом по галактике',
    "The Hitchhiker's Guide to the Galaxy",
    'Дуглас Адамс',
    'Douglas Adams',
    'science_fiction',
    'Научная фантастика',
    224,
  ),
  g('ww-fan-022', 'Нейромант', 'Neuromancer', 'Уильям Гибсон', 'William Gibson', 'science_fiction', 'Научная фантастика', 320),
  g('ww-fan-023', 'Марсианин', 'The Martian', 'Энди Вейер', 'Andy Weir', 'science_fiction', 'Научная фантастика', 384),
  g('ww-fan-024', 'Проект «Аве Мария»', 'Project Hail Mary', 'Энди Вейер', 'Andy Weir', 'science_fiction', 'Научная фантастика', 496),
  g('ww-fan-025', 'Голодные игры', 'The Hunger Games', 'Сьюзен Коллинз', 'Suzanne Collins', 'young_adult', 'Молодёжная литература', 384),
  g('ww-fan-026', 'И вспыхнет пламя', 'Catching Fire', 'Сьюзен Коллинз', 'Suzanne Collins', 'young_adult', 'Молодёжная литература', 400),
  g('ww-fan-027', 'Сойка-пересмешница', 'Mockingjay', 'Сьюзен Коллинз', 'Suzanne Collins', 'young_adult', 'Молодёжная литература', 400),
  g('ww-fan-028', 'Дивергент', 'Divergent', 'Вероника Рот', 'Veronica Roth', 'young_adult', 'Молодёжная литература', 496),
  g('ww-fan-029', 'Сумерки', 'Twilight', 'Стефани Майер', 'Stephenie Meyer', 'young_adult', 'Молодёжная литература', 512),
  g('ww-fan-030', 'Имя ветра', 'The Name of the Wind', 'Патрик Ротфусс', 'Patrick Rothfuss', 'fantasy', 'Фэнтези', 736),

  // —— Ужасы / триллеры ——
  g('ww-hor-001', 'Сияние', 'The Shining', 'Стивен Кинг', 'Stephen King', 'horror', 'Ужасы', 688),
  g('ww-hor-002', 'Оно', 'It', 'Стивен Кинг', 'Stephen King', 'horror', 'Ужасы', 1138),
  g('ww-hor-003', 'Кладбище домашних животных', 'Pet Sematary', 'Стивен Кинг', 'Stephen King', 'horror', 'Ужасы', 416),
  g('ww-hor-004', 'Мизери', 'Misery', 'Стивен Кинг', 'Stephen King', 'horror', 'Ужасы', 368),
  g('ww-hor-005', 'Зелёная миля', 'The Green Mile', 'Стивен Кинг', 'Stephen King', 'fiction', 'Художественная литература', 432),
  g('ww-hor-006', '11/22/63', '11/22/63', 'Стивен Кинг', 'Stephen King', 'fiction', 'Художественная литература', 880),
  g('ww-hor-007', 'Дракула', 'Dracula', 'Брэм Стокер', 'Bram Stoker', 'horror', 'Ужасы', 432),
  g('ww-hor-008', 'Франкенштейн', 'Frankenstein', 'Мэри Шелли', 'Mary Shelley', 'horror', 'Ужасы', 288),
  g('ww-hor-009', 'Исчезнувшая', 'Gone Girl', 'Гиллиан Флинн', 'Gillian Flynn', 'thriller', 'Триллер', 432),
  g('ww-hor-010', 'Девушка в поезде', 'The Girl on the Train', 'Пола Хокинс', 'Paula Hawkins', 'thriller', 'Триллер', 336),
  g('ww-hor-011', 'Молчание ягнят', 'The Silence of the Lambs', 'Томас Харрис', 'Thomas Harris', 'thriller', 'Триллер', 368),

  // —— Романтика ——
  g('ww-rom-001', 'Нормальные люди', 'Normal People', 'Салли Руни', 'Sally Rooney', 'romance', 'Романтика', 288),
  g('ww-rom-002', 'Дневник памяти', 'The Notebook', 'Николас Спаркс', 'Nicholas Sparks', 'romance', 'Романтика', 224),
  g('ww-rom-003', 'Виноваты звёзды', 'The Fault in Our Stars', 'Джон Грин', 'John Green', 'young_adult', 'Молодёжная литература', 320),
  g(
    'ww-rom-004',
    'Гордость и предубеждение и зомби',
    'Pride and Prejudice and Zombies',
    'Сет Грэм-Смит',
    'Seth Grahame-Smith',
    'fiction',
    'Художественная литература',
    320,
  ),
  g('ww-rom-005', 'Чудо', 'Wonder', 'Р. Дж. Паласио', 'R. J. Palacio', 'young_adult', 'Молодёжная литература', 320),

  // —— Нон-фикшн / психология ——
  g(
    'nf-001',
    'Sapiens. Краткая история человечества',
    'Sapiens: A Brief History of Humankind',
    'Юваль Ной Харари',
    'Yuval Noah Harari',
    'nonfiction',
    'Нон-фикшн',
    512,
  ),
  g('nf-002', 'Homo Deus', 'Homo Deus', 'Юваль Ной Харари', 'Yuval Noah Harari', 'nonfiction', 'Нон-фикшн', 448),
  g('nf-003', 'Атомные привычки', 'Atomic Habits', 'Джеймс Клир', 'James Clear', 'self-help', 'Саморазвитие', 320),
  g('nf-004', 'Думай медленно… решай быстро', 'Thinking, Fast and Slow', 'Даниэль Канеман', 'Daniel Kahneman', 'psychology', 'Психология', 656),
  g('nf-005', 'Тонкое искусство пофигизма', 'The Subtle Art of Not Giving a F*ck', 'Марк Мэнсон', 'Mark Manson', 'self-help', 'Саморазвитие', 224),
  g('nf-006', 'Как завоевывать друзей', 'How to Win Friends and Influence People', 'Дейл Карнеги', 'Dale Carnegie', 'self-help', 'Саморазвитие', 288),
  g('nf-007', 'Богатый папа, бедный папа', 'Rich Dad Poor Dad', 'Роберт Кийосаки', 'Robert Kiyosaki', 'self-help', 'Саморазвитие', 336),
  g(
    'nf-008',
    '7 навыков высокоэффективных людей',
    'The 7 Habits of Highly Effective People',
    'Стивен Кови',
    'Stephen Covey',
    'self-help',
    'Саморазвитие',
    432,
  ),
  g('nf-009', 'Чёрный лебедь', 'The Black Swan', 'Нассим Николас Талеб', 'Nassim Nicholas Taleb', 'nonfiction', 'Нон-фикшн', 480),
  g('nf-010', 'Антихрупкость', 'Antifragile', 'Нассим Николас Талеб', 'Nassim Nicholas Taleb', 'nonfiction', 'Нон-фикшн', 544),
  g('nf-011', 'От нуля к единице', 'Zero to One', 'Питер Тиль', 'Peter Thiel', 'nonfiction', 'Нон-фикшн', 224),
  g('nf-012', 'Эго — это враг', 'Ego Is the Enemy', 'Райан Холидей', 'Ryan Holiday', 'self-help', 'Саморазвитие', 256),
  g('nf-013', 'Почему мы спим', 'Why We Sleep', 'Мэттью Уолкер', 'Matthew Walker', 'nonfiction', 'Нон-фикшн', 368),
  g('nf-014', 'Сила привычки', 'The Power of Habit', 'Чарльз Дахигг', 'Charles Duhigg', 'self-help', 'Саморазвитие', 400),
  g('nf-015', 'Думай как математик', 'A Mind for Numbers', 'Барбара Оакли', 'Barbara Oakley', 'self-help', 'Саморазвитие', 336),
  g('nf-016', 'Мужество быть нелюбимым', 'The Courage to Be Disliked', 'Ичиро Кишими', 'Ichiro Kishimi', 'psychology', 'Психология', 288),
  g('nf-017', 'Человек в поисках смысла', "Man's Search for Meaning", 'Виктор Франкл', 'Viktor Frankl', 'psychology', 'Психология', 192),
  g('nf-018', 'Эмоциональный интеллект', 'Emotional Intelligence', 'Дэниел Гоулман', 'Daniel Goleman', 'psychology', 'Психология', 368),
  g('nf-019', 'Поток', 'Flow', 'Михай Чиксентмихайи', 'Mihaly Csikszentmihalyi', 'psychology', 'Психология', 336),
  g('nf-020', 'Искусство любить', 'The Art of Loving', 'Эрих Фромм', 'Erich Fromm', 'psychology', 'Психология', 160),
  g('nf-021', 'Бегство от свободы', 'Escape from Freedom', 'Эрих Фромм', 'Erich Fromm', 'psychology', 'Психология', 288),
  g('nf-022', 'Краткая история времени', 'A Brief History of Time', 'Стивен Хокинг', 'Stephen Hawking', 'nonfiction', 'Нон-фикшн', 256),
  g('nf-023', 'Космос', 'Cosmos', 'Карл Саган', 'Carl Sagan', 'nonfiction', 'Нон-фикшн', 384),
  g('nf-024', 'Думай и богатей', 'Think and Grow Rich', 'Наполеон Хилл', 'Napoleon Hill', 'self-help', 'Саморазвитие', 320),
  g('nf-025', 'От хорошего к великому', 'Good to Great', 'Джим Коллинз', 'Jim Collins', 'nonfiction', 'Нон-фикшн', 320),

  // —— Ещё популярные ——
  g('ex-001', 'Шантарам', 'Shantaram', 'Грегори Дэвид Робертс', 'Gregory David Roberts', 'fiction', 'Художественная литература', 864),
  g('ex-002', 'Тень горы', 'The Mountain Shadow', 'Грегори Дэвид Робертс', 'Gregory David Roberts', 'fiction', 'Художественная литература', 880),
  g('ex-003', 'Атлант расправил плечи', 'Atlas Shrugged', 'Айн Рэнд', 'Ayn Rand', 'fiction', 'Художественная литература', 1168),
  g('ex-004', 'Источник', 'The Fountainhead', 'Айн Рэнд', 'Ayn Rand', 'fiction', 'Художественная литература', 752),
  g('ex-005', 'Игра Эндера', "Ender's Game", 'Орсон Скотт Кард', 'Orson Scott Card', 'science_fiction', 'Научная фантастика', 352),
  g('ex-006', 'Бегущий в лабиринте', 'The Maze Runner', 'Джеймс Дэшнер', 'James Dashner', 'young_adult', 'Молодёжная литература', 384),
  g('ex-007', 'Первому игроку приготовиться', 'Ready Player One', 'Эрнест Клайн', 'Ernest Cline', 'science_fiction', 'Научная фантастика', 384),
  g('ex-008', 'Пойди поставь сторожа', 'Go Set a Watchman', 'Харпер Ли', 'Harper Lee', 'fiction', 'Художественная литература', 288),
  g('ex-009', 'Девушка с татуировкой дракона', 'The Girl with the Dragon Tattoo', 'Стиг Ларссон', 'Stieg Larsson', 'thriller', 'Триллер', 672),
  g('ex-010', 'Девушка, которая играла с огнём', 'The Girl Who Played with Fire', 'Стиг Ларссон', 'Stieg Larsson', 'thriller', 'Триллер', 640),
  g('ex-011', 'Жизнь Пи', 'Life of Pi', 'Янн Мартел', 'Yann Martel', 'fiction', 'Художественная литература', 352),
  g('ex-012', 'Облачный атлас', 'Cloud Atlas', 'Дэвид Митчелл', 'David Mitchell', 'fiction', 'Художественная литература', 544),
  g('ex-013', 'Кладбище забытых книг. Игра ангела', "The Angel's Game", 'Карлос Руис Сафон', 'Carlos Ruiz Zafón', 'mystery', 'Детектив', 512),
  g('ex-014', 'Правила виноделов', 'The Cider House Rules', 'Джон Ирвинг', 'John Irving', 'fiction', 'Художественная литература', 640),
  g('ex-015', 'Мир Софии', "Sophie's World", 'Юстейн Гордер', 'Jostein Gaarder', 'fiction', 'Художественная литература', 544),
  g('ex-016', 'Цветы для Элджернона', 'Flowers for Algernon', 'Дэниел Киз', 'Daniel Keyes', 'science_fiction', 'Научная фантастика', 320),
  g('ex-017', 'Повелитель мух', 'Lord of the Flies', 'Уильям Голдинг', 'William Golding', 'classics', 'Классика', 256),
  g('ex-018', 'О дивный новый мир', 'Brave New World', 'Олдос Хаксли', 'Aldous Huxley', 'classics', 'Классика', 288),
  g('ex-019', 'Процесс', 'The Trial', 'Франц Кафка', 'Franz Kafka', 'classics', 'Классика', 256),
  g('ex-020', 'Превращение', 'The Metamorphosis', 'Франц Кафка', 'Franz Kafka', 'classics', 'Классика', 80),
  g('ex-021', 'Старик и море', 'The Old Man and the Sea', 'Эрнест Хемингуэй', 'Ernest Hemingway', 'classics', 'Классика', 128),
  g('ex-022', 'Прощай, оружие!', 'A Farewell to Arms', 'Эрнест Хемингуэй', 'Ernest Hemingway', 'classics', 'Классика', 352),
  g('ex-023', 'По ком звонит колокол', 'For Whom the Bell Tolls', 'Эрнест Хемингуэй', 'Ernest Hemingway', 'classics', 'Классика', 480),
  g('ex-024', 'Улисс', 'Ulysses', 'Джеймс Джойс', 'James Joyce', 'classics', 'Классика', 784),
  g('ex-025', 'Пикник у Висячей скалы', 'Picnic at Hanging Rock', 'Джоан Линдсей', 'Joan Lindsay', 'fiction', 'Художественная литература', 224),
  g('ex-026', 'Книжный вор', 'The Book Thief', 'Маркус Зусак', 'Markus Zusak', 'historical_fiction', 'Историческая проза', 584),
  g('ex-027', 'Ночной цирк', 'The Night Circus', 'Эрин Моргенштерн', 'Erin Morgenstern', 'fantasy', 'Фэнтези', 512),
  g('ex-028', 'Песнь Ахилла', 'The Song of Achilles', 'Мадлен Миллер', 'Madeline Miller', 'fiction', 'Художественная литература', 416),
  g('ex-029', 'Цирцея', 'Circe', 'Мадлен Миллер', 'Madeline Miller', 'fiction', 'Художественная литература', 400),
  g('ex-030', 'Унесённые ветром', 'Gone with the Wind', 'Маргарет Митчелл', 'Margaret Mitchell', 'historical_fiction', 'Историческая проза', 1024),
  g('ex-031', 'Мессия Дюны', 'Dune Messiah', 'Фрэнк Герберт', 'Frank Herbert', 'science_fiction', 'Научная фантастика', 272),
  g('ex-032', 'Американские боги', 'American Gods', 'Нил Гейман', 'Neil Gaiman', 'fantasy', 'Фэнтези', 624),
  g('ex-033', 'Коралина', 'Coraline', 'Нил Гейман', 'Neil Gaiman', 'fantasy', 'Фэнтези', 192),
  g('ex-034', 'Никогде', 'Neverwhere', 'Нил Гейман', 'Neil Gaiman', 'fantasy', 'Фэнтези', 400),
  g('ex-035', 'Благие знамения', 'Good Omens', 'Терри Пратчетт, Нил Гейман', 'Terry Pratchett, Neil Gaiman', 'fantasy', 'Фэнтези', 416),
  g('ex-036', 'Цвет волшебства', 'The Colour of Magic', 'Терри Пратчетт', 'Terry Pratchett', 'fantasy', 'Фэнтези', 288),
  g('ex-037', 'Стража! Стража!', 'Guards! Guards!', 'Терри Пратчетт', 'Terry Pratchett', 'fantasy', 'Фэнтези', 416),
  g('ex-038', 'Ведьмак. Последнее желание', 'The Last Wish', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 288),
  g('ex-039', 'Ведьмак. Меч предназначения', 'Sword of Destiny', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 384),
  g('ex-040', 'Кровь эльфов', 'Blood of Elves', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 320),
  g('ex-041', 'Час Презрения', 'Time of Contempt', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 352),
  g('ex-042', 'Крещение огнём', 'Baptism of Fire', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 352),
  g('ex-043', 'Башня Ласточки', 'The Tower of the Swallow', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 448),
  g('ex-044', 'Владычица Озера', 'The Lady of the Lake', 'Анджей Сапковский', 'Andrzej Sapkowski', 'fantasy', 'Фэнтези', 544),
  g('ex-045', 'Питер Пен', 'Peter Pan', 'Джеймс Барри', 'J. M. Barrie', 'classics', 'Классика', 192),
  g('ex-046', 'Алиса в Стране чудес', "Alice's Adventures in Wonderland", 'Льюис Кэрролл', 'Lewis Carroll', 'classics', 'Классика', 192),
  g('ex-047', 'Винни-Пух', 'Winnie-the-Pooh', 'Алан Милн', 'A. A. Milne', 'classics', 'Классика', 176),
  g('ex-048', 'Маугли', 'The Jungle Book', 'Редьярд Киплинг', 'Rudyard Kipling', 'classics', 'Классика', 240),
  g('ex-049', 'Белый Клык', 'White Fang', 'Джек Лондон', 'Jack London', 'adventure', 'Приключения', 288),
  g('ex-050', 'Зов предков', 'The Call of the Wild', 'Джек Лондон', 'Jack London', 'adventure', 'Приключения', 160),
  g('ex-051', 'Мартин Иден', 'Martin Eden', 'Джек Лондон', 'Jack London', 'classics', 'Классика', 480),
  g('ex-052', 'Робинзон Крузо', 'Robinson Crusoe', 'Даниэль Дефо', 'Daniel Defoe', 'adventure', 'Приключения', 320),
  g('ex-053', 'Остров сокровищ', 'Treasure Island', 'Роберт Льюис Стивенсон', 'Robert Louis Stevenson', 'adventure', 'Приключения', 288),
  g('ex-054', 'Двадцать тысяч лье под водой', 'Twenty Thousand Leagues Under the Seas', 'Жюль Верн', 'Jules Verne', 'adventure', 'Приключения', 448),
  g('ex-055', 'Вокруг света за 80 дней', 'Around the World in Eighty Days', 'Жюль Верн', 'Jules Verne', 'adventure', 'Приключения', 256),
  g('ex-056', 'Таинственный остров', 'The Mysterious Island', 'Жюль Верн', 'Jules Verne', 'adventure', 'Приключения', 640),
  g('ex-057', 'Гарри Поттер и Проклятое дитя', 'Harry Potter and the Cursed Child', 'Джоан Роулинг', 'J. K. Rowling', 'fantasy', 'Фэнтези', 336),
  g('ex-058', 'Эрагон', 'Eragon', 'Кристофер Паолини', 'Christopher Paolini', 'fantasy', 'Фэнтези', 544),
];
