/**
 * Downloads Open Library covers for POPULAR_BOOKS_CATALOG into src/assets/catalogCovers
 * and generates src/utils/catalogCoverAssets.ts with static require() map.
 *
 * Usage: node scripts/downloadCatalogCovers.cjs
 */
const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

const ROOT = path.resolve(__dirname, '..');
const CATALOG_FILE = path.join(ROOT, 'src/utils/popularBooksCatalog.ts');
const OUT_DIR = path.join(ROOT, 'src/assets/catalogCovers');
const OUT_MAP = path.join(ROOT, 'src/utils/catalogCoverAssets.ts');
const OL_SEARCH = 'https://openlibrary.org/search.json';

const CONCURRENCY = 4;
const MIN_BYTES = 1500;

function parseCatalog(filePath) {
  const src = fs.readFileSync(filePath, 'utf8');
  const re =
    /g\(\s*'([^']+)'\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'\s*,\s*'((?:\\'|[^'])*)'/g;
  const books = [];
  let m;
  while ((m = re.exec(src))) {
    books.push({
      id: m[1],
      titleRu: m[2].replace(/\\'/g, "'"),
      titleEn: m[3].replace(/\\'/g, "'"),
      authorRu: m[4].replace(/\\'/g, "'"),
      authorEn: m[5].replace(/\\'/g, "'"),
    });
  }
  return books;
}

function fetchJson(url) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith('https') ? https : http;
    const req = lib.get(url, { headers: { Accept: 'application/json', 'User-Agent': 'BookDeskCoverBot/1.0' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        fetchJson(res.headers.location).then(resolve).catch(reject);
        return;
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        try {
          resolve(JSON.parse(Buffer.concat(chunks).toString('utf8')));
        } catch (e) {
          reject(e);
        }
      });
    });
    req.on('error', reject);
    req.setTimeout(20000, () => {
      req.destroy(new Error('timeout'));
    });
  });
}

function downloadFile(url, dest) {
  return new Promise((resolve, reject) => {
    const lib = url.startsWith('https') ? https : http;
    const req = lib.get(url, { headers: { 'User-Agent': 'BookDeskCoverBot/1.0' }, timeout: 25000 }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        downloadFile(res.headers.location, dest).then(resolve).catch(reject);
        return;
      }
      if (res.statusCode !== 200) {
        reject(new Error(`HTTP ${res.statusCode}`));
        res.resume();
        return;
      }
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => {
        const buf = Buffer.concat(chunks);
        if (buf.length < MIN_BYTES) {
          reject(new Error(`too small ${buf.length}`));
          return;
        }
        fs.writeFileSync(dest, buf);
        resolve(buf.length);
      });
    });
    req.on('error', reject);
    req.setTimeout(25000, () => req.destroy(new Error('timeout')));
  });
}

async function findCoverUrl(title, author) {
  const attempts = [
    `${OL_SEARCH}?title=${encodeURIComponent(title)}&author=${encodeURIComponent(author)}&limit=12&fields=cover_i,cover_edition_key,isbn,edition_count`,
    `${OL_SEARCH}?q=${encodeURIComponent(`${title} ${author}`)}&limit=12&fields=cover_i,cover_edition_key,isbn,edition_count`,
    `${OL_SEARCH}?title=${encodeURIComponent(title)}&limit=12&fields=cover_i,cover_edition_key,isbn,edition_count`,
  ];

  for (const url of attempts) {
    try {
      const data = await fetchJson(url);
      const docs = Array.isArray(data?.docs) ? data.docs : [];
      const ranked = [...docs].sort((a, b) => (b.edition_count || 0) - (a.edition_count || 0));
      for (const doc of ranked) {
        if (doc.cover_i) {
          return `https://covers.openlibrary.org/b/id/${doc.cover_i}-M.jpg?default=false`;
        }
        if (doc.cover_edition_key) {
          return `https://covers.openlibrary.org/b/olid/${doc.cover_edition_key}-M.jpg?default=false`;
        }
        const isbn = Array.isArray(doc.isbn) ? doc.isbn.find((v) => String(v).length >= 10) : null;
        if (isbn) {
          return `https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg?default=false`;
        }
      }
    } catch {
      // try next
    }
  }
  return null;
}

async function mapLimit(items, limit, worker) {
  const results = new Array(items.length);
  let idx = 0;
  async function run() {
    while (idx < items.length) {
      const i = idx++;
      results[i] = await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, () => run()));
  return results;
}

function writeAssetMap(ids) {
  const lines = [
    "import { ImageSourcePropType } from 'react-native';",
    '',
    '/** Auto-generated by scripts/downloadCatalogCovers.mjs — do not edit by hand */',
    'export const CATALOG_COVER_ASSETS: Record<string, ImageSourcePropType> = {',
    ...ids.map((id) => `  '${id}': require('../assets/catalogCovers/${id}.jpg'),`),
    '};',
    '',
    'export const hasCatalogCover = (id: string): boolean => Boolean(CATALOG_COVER_ASSETS[id]);',
    '',
  ];
  fs.writeFileSync(OUT_MAP, lines.join('\n'), 'utf8');
}

async function main() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const books = parseCatalog(CATALOG_FILE);
  console.log(`Catalog books: ${books.length}`);

  let ok = 0;
  let skip = 0;
  let fail = 0;
  const successIds = [];

  await mapLimit(books, CONCURRENCY, async (book) => {
    const dest = path.join(OUT_DIR, `${book.id}.jpg`);
    if (fs.existsSync(dest) && fs.statSync(dest).size >= MIN_BYTES) {
      skip += 1;
      successIds.push(book.id);
      process.stdout.write(`SKIP ${book.id}\n`);
      return;
    }

    try {
      const url =
        (await findCoverUrl(book.titleEn, book.authorEn)) ||
        (await findCoverUrl(book.titleRu, book.authorRu)) ||
        (await findCoverUrl(book.titleEn, ''));
      if (!url) {
        fail += 1;
        process.stdout.write(`MISS ${book.id} ${book.titleEn}\n`);
        return;
      }
      const size = await downloadFile(url, dest);
      ok += 1;
      successIds.push(book.id);
      process.stdout.write(`OK   ${book.id} (${size}b)\n`);
    } catch (e) {
      fail += 1;
      if (fs.existsSync(dest)) fs.unlinkSync(dest);
      process.stdout.write(`FAIL ${book.id} ${e.message}\n`);
    }
  });

  successIds.sort();
  writeAssetMap(successIds);
  console.log(`\nDone. downloaded=${ok} cached=${skip} failed=${fail} mapped=${successIds.length}`);
  console.log(`Assets: ${OUT_DIR}`);
  console.log(`Map: ${OUT_MAP}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
